----------> uses
# use TDAQPolicy *  (no_version_directory)
#   use TDAQCPolicy *  (no_version_directory)
#     use TDAQCPolicyInt * TDAQCPolicy (no_version_directory)
#   use TDAQExternal *  (no_version_directory)
#     use TDAQCPolicy *  (no_version_directory)
#     use DQMCExternal *  (no_version_directory)
#       use TDAQCExternal *  (no_version_directory)
#         use TDAQCPolicy *  (no_version_directory)
#       use LCG_Configuration v*  (no_version_directory)
#         use LCG_Platforms *  (no_version_directory)
# use ROSModules *  (no_version_directory)
#   use TDAQPolicy *  (no_version_directory)
#   use ROSCore *  (no_version_directory)
#     use ROSBufferManagement *  (no_version_directory)
#       use ROSMemoryPool *  (no_version_directory)
#         use cmem_rcc *  (no_version_directory)
#           use TDAQPolicy *  (no_version_directory)
#           use rcc_error *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#           use ROSGetInput *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#           use DFDebug *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#         use rcc_time_stamp *  (no_version_directory)
#           use TDAQPolicy *  (no_version_directory)
#           use rcc_error *  (no_version_directory)
#           use ROSGetInput *  (no_version_directory)
#           use DFDebug *  (no_version_directory)
#         use DFExceptions *  (no_version_directory)
#           use DataflowPolicy *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#           use ers *  (no_version_directory)
#             use TDAQCPolicy *  (no_version_directory)
#             use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#               use TDAQCPolicy *  (no_version_directory)
#               use TDAQCExternal *  (no_version_directory)
#             use Python * TDAQCExternal (no_version_directory) (native_version=2.7.6)
#               use TDAQCPolicy *  (no_version_directory)
#               use TDAQCExternal *  (no_version_directory)
#         use DFDebug *  (no_version_directory)
#         use rcc_error *  (no_version_directory)
#         use ROSGetInput *  (no_version_directory)
#         use ROSObjectAllocation *  (no_version_directory)
#           use DFThreads *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#             use rcc_time_stamp *  (no_version_directory)
#             use cmem_rcc *  (no_version_directory)
#           use ROSGetInput *  (no_version_directory)
#       use ROSObjectAllocation *  (no_version_directory)
#       use DFExceptions *  (no_version_directory)
#       use ROSGetInput *  (no_version_directory)
#       use ers *  (no_version_directory)
#       use rcc_time_stamp *  (no_version_directory)
#     use ROSObjectAllocation *  (no_version_directory)
#     use ROSEventFragment *  (no_version_directory)
#       use TDAQPolicy *  (no_version_directory)
#       use ROSBufferManagement *  (no_version_directory)
#       use DFDebug *  (no_version_directory)
#       use emon *  (no_version_directory)
#         use eformat *  (no_version_directory)
#           use ers *  (no_version_directory)
#           use Python * TDAQCExternal (no_version_directory) (native_version=2.7.6)
#         use ProcessManager *  (no_version_directory)
#           use TDAQPolicy *  (no_version_directory)
#           use ipc *  (no_version_directory)
#             use OnlinePolicy *  (no_version_directory)
#               use TDAQPolicy *  (no_version_directory)
#               use TDAQExtJars *  (no_version_directory)
#                 use TDAQPolicy *  (no_version_directory)
#             use owl *  (no_version_directory)
#               use OnlinePolicy *  (no_version_directory)
#               use omni *  (no_version_directory)
#                 use OnlinePolicy *  (no_version_directory)
#                 use Python * TDAQCExternal (no_version_directory) (native_version=2.7.6)
#               use ers *  (no_version_directory)
#               use system *  (no_version_directory)
#                 use TDAQPolicy *  (no_version_directory)
#                 use ers *  (no_version_directory)
#             use cmdl *  (no_version_directory)
#               use OnlinePolicy *  (no_version_directory)
#             use omni *  (no_version_directory)
#             use ers *  (no_version_directory)
#             use Jers *  (no_version_directory)
#               use OnlinePolicy *  (no_version_directory)
#             use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#           use RCInfo *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#             use is *  (no_version_directory)
#               use OnlinePolicy *  (no_version_directory)
#               use owl *  (no_version_directory)
#               use cmdl *  (no_version_directory)
#               use rdb *  (no_version_directory)
#                 use OnlinePolicy *  (no_version_directory)
#                 use ipc *  (no_version_directory)
#               use tbb *  (no_version_directory)
#                 use TDAQPolicy *  (no_version_directory)
#               use xmext *  (no_version_directory)
#                 use OnlinePolicy *  (no_version_directory)
#               use jeformat *  (no_version_directory)
#                 use OnlinePolicy *  (no_version_directory)
#           use is *  (no_version_directory)
#           use ResourceManager *  (no_version_directory)
#             use OnlinePolicy *  (no_version_directory)
#             use cmdl *  (no_version_directory)
#             use omni *  (no_version_directory)
#             use ers *  (no_version_directory)
#             use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#             use owl *  (no_version_directory)
#             use ipc *  (no_version_directory)
#             use config *  (no_version_directory)
#               use OnlinePolicy *  (no_version_directory)
#               use ers *  (no_version_directory)
#               use owl *  (no_version_directory)
#               use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#               use Python * TDAQCExternal (no_version_directory) (native_version=2.7.6)
#             use dal *  (no_version_directory)
#               use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#               use OnlinePolicy *  (no_version_directory)
#               use config *  (no_version_directory)
#             use AccessManager *  (no_version_directory)
#               use OnlinePolicy *  (no_version_directory)
#               use ers *  (no_version_directory)
#               use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#               use XercesC * TDAQExternal (no_version_directory)
#                 use TDAQPolicy *  (no_version_directory)
#                 use TDAQExternal *  (no_version_directory)
#           use ers *  (no_version_directory)
#           use system *  (no_version_directory)
#           use owl *  (no_version_directory)
#           use omni *  (no_version_directory)
#           use DFThreads *  (no_version_directory)
#           use AccessManager *  (no_version_directory)
#           use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#           use tmgr *  (no_version_directory)
#             use TDAQPolicy *  (no_version_directory)
#         use genconfig *  (no_version_directory)
#           use OnlinePolicy *  (no_version_directory)
#       use DFExceptions *  (no_version_directory)
#       use rcc_time_stamp *  (no_version_directory)
#       use robin_ppc *  (no_version_directory)
#         use TDAQPolicy *  (no_version_directory)
#       use ROSGetInput *  (no_version_directory)
#       use ROSMemoryPool *  (no_version_directory)
#       use ROSObjectAllocation *  (no_version_directory)
#       use ROSUtilities *  (no_version_directory)
#         use DFExceptions *  (no_version_directory)
#         use DFThreads *  (no_version_directory)
#         use ers *  (no_version_directory)
#       use TTCInfo *  (no_version_directory)
#         use TDAQPolicy *  (no_version_directory)
#         use is *  (no_version_directory)
#     use ROSEventInputManager *  (no_version_directory)
#       use ROSMemoryPool *  (no_version_directory)
#       use cmem_rcc *  (no_version_directory)
#       use rcc_time_stamp *  (no_version_directory)
#       use rcc_error *  (no_version_directory)
#       use ROSUtilities *  (no_version_directory)
#       use ROSGetInput *  (no_version_directory)
#       use DFExceptions *  (no_version_directory)
#     use ROSMemoryPool *  (no_version_directory)
#     use DFThreads *  (no_version_directory)
#     use DFSubSystemItem *  (no_version_directory)
#       use DFExceptions *  (no_version_directory)
#       use ROSUtilities *  (no_version_directory)
#       use DFThreads *  (no_version_directory)
#     use is *  (no_version_directory)
#     use rcc_time_stamp *  (no_version_directory)
#     use DFExceptions *  (no_version_directory)
#     use DFDebug *  (no_version_directory)
#     use RunControl *  (no_version_directory)
#       use OnlinePolicy *  (no_version_directory)
#       use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#       use Python * TDAQCExternal (no_version_directory) (native_version=2.7.6)
#       use CppUnit * TDAQExternal (no_version_directory)
#         use TDAQPolicy *  (no_version_directory)
#         use TDAQExternal *  (no_version_directory)
#       use tbb *  (no_version_directory)
#       use ers *  (no_version_directory)
#       use ipc *  (no_version_directory)
#       use config *  (no_version_directory)
#       use dal *  (no_version_directory)
#       use ProcessManager *  (no_version_directory)
#       use RCInfo *  (no_version_directory)
#       use is *  (no_version_directory)
#       use ExpertSystemInterface *  (no_version_directory)
#         use TDAQPolicy *  (no_version_directory)
#         use ipc *  (no_version_directory)
#         use ers *  (no_version_directory)
#         use TestManager *  (no_version_directory)
#           use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#           use tbb *  (no_version_directory)
#           use ers *  (no_version_directory)
#           use ProcessManager *  (no_version_directory)
#           use config *  (no_version_directory)
#           use genconfig *  (no_version_directory)
#           use dal *  (no_version_directory)
#           use is *  (no_version_directory)
#           use tmgr *  (no_version_directory)
#         use tmgr *  (no_version_directory)
#         use dal *  (no_version_directory)
#       use owl *  (no_version_directory)
#       use ResourceManager *  (no_version_directory)
#       use rn *  (no_version_directory)
#       use DFConfiguration *  (no_version_directory)
#         use genconfig *  (no_version_directory)
#         use dal *  (no_version_directory)
#         use is *  (no_version_directory)
#         use emon *  (no_version_directory)
#       use eformat *  (no_version_directory)
#       use TriggerCommander *  (no_version_directory)
#         use TDAQPolicy *  (no_version_directory)
#         use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#         use AccessManager *  (no_version_directory)
#         use ers *  (no_version_directory)
#         use ipc *  (no_version_directory)
#         use is *  (no_version_directory)
#         use RCInfo *  (no_version_directory)
#         use system *  (no_version_directory)
#       use system *  (no_version_directory)
#       use AccessManager *  (no_version_directory)
#       use dvs *  (no_version_directory)
#         use ers *  (no_version_directory)
#         use system *  (no_version_directory)
#         use ProcessManager *  (no_version_directory)
#         use is *  (no_version_directory)
#         use DFConfiguration *  (no_version_directory)
#         use TestManager *  (no_version_directory)
#       use TestManager *  (no_version_directory)
#       use tmgr *  (no_version_directory)
#       use TTCInfo *  (no_version_directory)
#     use ROSUtilities *  (no_version_directory)
#     use DFConfiguration *  (no_version_directory)
#     use tbb *  (no_version_directory)
#     use ROOT * DQMCExternal (no_version_directory)
#       use TDAQCPolicy *  (no_version_directory)
#       use DQMCExternal *  (no_version_directory)
#       use xrootd * DQMCExternal (no_version_directory)
#         use TDAQCPolicy *  (no_version_directory)
#         use DQMCExternal *  (no_version_directory)
#     use monsvc *  (no_version_directory)
#       use TDAQPolicy *  (no_version_directory)
#       use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#       use ROOT * DQMCExternal (no_version_directory)
#       use config *  (no_version_directory)
#       use genconfig *  (no_version_directory)
#       use is *  (no_version_directory)
#       use oh *  (no_version_directory)
#         use OnlinePolicy *  (no_version_directory)
#         use cmdl *  (no_version_directory)
#         use is *  (no_version_directory)
#         use RunControl *  (no_version_directory)
#         use ROOT * DQMCExternal (no_version_directory)
#       use ers *  (no_version_directory)
#   use ROSBufferManagement *  (no_version_directory)
#   use ROSEventInputManager *  (no_version_directory)
#   use DFSubSystemItem *  (no_version_directory)
#   use ROSEventFragment *  (no_version_directory)
#   use ROSfilar *  (no_version_directory)
#     use TDAQPolicy *  (no_version_directory)
#     use ROSEventFragment *  (no_version_directory)
#     use tmgr *  (no_version_directory)
#     use io_rcc *  (no_version_directory)
#       use TDAQPolicy *  (no_version_directory)
#       use rcc_error *  (no_version_directory)
#       use ROSGetInput *  (no_version_directory)
#       use DFDebug *  (no_version_directory)
#     use cmdl *  (no_version_directory)
#     use cmem_rcc *  (no_version_directory)
#     use DFDebug *  (no_version_directory)
#     use io_rcc *  (no_version_directory)
#     use ProcessManager *  (no_version_directory)
#     use rcc_error *  (no_version_directory)
#     use rcc_time_stamp *  (no_version_directory)
#     use ROSBufferManagement *  (no_version_directory)
#     use ROSGetInput *  (no_version_directory)
#     use ROSMemoryPool *  (no_version_directory)
#   use ROSslink *  (no_version_directory)
#     use TDAQPolicy *  (no_version_directory)
#     use tmgr *  (no_version_directory)
#     use ROSEventFragment *  (no_version_directory)
#     use io_rcc *  (no_version_directory)
#     use cmdl *  (no_version_directory)
#     use DFDebug *  (no_version_directory)
#     use ProcessManager *  (no_version_directory)
#     use rcc_error *  (no_version_directory)
#     use rcc_time_stamp *  (no_version_directory)
#     use ROSBufferManagement *  (no_version_directory)
#     use ROSMemoryPool *  (no_version_directory)
#   use ROSRobin *  (no_version_directory)
#     use TDAQPolicy *  (no_version_directory)
#     use ROSEventFragment *  (no_version_directory)
#     use cmem_rcc *  (no_version_directory)
#     use robin_ppc *  (no_version_directory)
#     use DFExceptions *  (no_version_directory)
#     use tmgr *  (no_version_directory)
#     use cmdl *  (no_version_directory)
#     use DFDebug *  (no_version_directory)
#     use DFThreads *  (no_version_directory)
#     use ProcessManager *  (no_version_directory)
#     use rcc_error *  (no_version_directory)
#     use rcc_time_stamp *  (no_version_directory)
#     use ROSBufferManagement *  (no_version_directory)
#     use ROSGetInput *  (no_version_directory)
#     use ROSMemoryPool *  (no_version_directory)
#     use ROSUtilities *  (no_version_directory)
#   use ROSUtilities *  (no_version_directory)
#   use rcc_time_stamp *  (no_version_directory)
#   use eformat *  (no_version_directory)
#   use EventStorage *  (no_version_directory)
#     use TDAQCPolicy *  (no_version_directory)
#     use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#     use ers *  (no_version_directory)
#     use compression *  (no_version_directory)
#       use TDAQCPolicy *  (no_version_directory)
#       use Boost * TDAQCExternal (no_version_directory) (native_version=1.55.0_python2.7)
#       use ers *  (no_version_directory)
#   use robin_ppc *  (no_version_directory)
#   use ROSInterruptScheduler *  (no_version_directory)
#     use DFDebug *  (no_version_directory)
#     use DFExceptions *  (no_version_directory)
#     use DFThreads *  (no_version_directory)
#     use DFSubSystemItem *  (no_version_directory)
#     use ROSUtilities *  (no_version_directory)
#     use vme_rcc *  (no_version_directory)
#       use io_rcc *  (no_version_directory)
#       use cmem_rcc *  (no_version_directory)
#       use rcc_time_stamp *  (no_version_directory)
#       use ROSGetInput *  (no_version_directory)
#       use DFDebug *  (no_version_directory)
#       use cmdl *  (no_version_directory)
#       use rcc_error *  (no_version_directory)
#     use ROSCore *  (no_version_directory)
#     use ROSRobin *  (no_version_directory)
#     use ROSEventFragment *  (no_version_directory)
#     use is *  (no_version_directory)
#     use rcc_error *  (no_version_directory)
#     use robin_ppc *  (no_version_directory)
#     use ROSBufferManagement *  (no_version_directory)
#     use ROSMemoryPool *  (no_version_directory)
#   use DFDebug *  (no_version_directory)
#   use DFExceptions *  (no_version_directory)
#   use DFThreads *  (no_version_directory)
#   use ipc *  (no_version_directory)
#   use is *  (no_version_directory)
#   use rcc_error *  (no_version_directory)
#   use ROSGetInput *  (no_version_directory)
#   use ROSMemoryPool *  (no_version_directory)
# use DFSubSystemItem *  (no_version_directory)
# use DFDebug *  (no_version_directory)
# use DFThreads *  (no_version_directory)
# use ROSMemoryPool *  (no_version_directory)
# use ROSEventFragment *  (no_version_directory)
# use ROSBufferManagement *  (no_version_directory)
# use oh *  (no_version_directory)
#
# Selection :
use CMT v1r25p20130606 (/afs/cern.ch/sw/contrib)
use rn rn-02-00-08  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use LCG_Platforms v1  (/afs/cern.ch/atlas/project/tdaq/inst/LCGCMT/LCGCMT_71)
use LCG_Configuration v1  (/afs/cern.ch/atlas/project/tdaq/inst/LCGCMT/LCGCMT_71)
use TDAQCPolicyInt v1r1p0 TDAQCPolicy (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use TDAQCPolicy TDAQCPolicy-00-18-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use TDAQCExternal TDAQCExternal-00-27-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use Python ${PYTHON_VERSION} TDAQCExternal (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use Boost ${BOOST_VERSION} TDAQCExternal (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use ers ers-00-15-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use compression compression-00-00-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use EventStorage EventStorage-01-37-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use eformat eformat-05-04-05  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00)
use DQMCExternal DQMCExternal-00-09-00  (/afs/cern.ch/atlas/project/tdaq/inst/dqm-common/dqm-common-00-37-00)
use xrootd ${XROOTD_VERSION} DQMCExternal (/afs/cern.ch/atlas/project/tdaq/inst/dqm-common/dqm-common-00-37-00)
use ROOT ${ROOT_VERSION} DQMCExternal (/afs/cern.ch/atlas/project/tdaq/inst/dqm-common/dqm-common-00-37-00)
use TDAQExternal TDAQExternal-00-23-06  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use TDAQPolicy TDAQPolicy-00-10-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use CppUnit ${CPPUNIT_VERSION} TDAQExternal (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use robin_ppc robin_ppc-00-00-132  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use tmgr tmgr-03-00-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use XercesC ${XERCESC_VERSION} TDAQExternal (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use tbb tbb-04-01-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use system system-00-00-16  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use TDAQExtJars TDAQExtJars-00-05-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use OnlinePolicy OnlinePolicy-00-29-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use genconfig genconfig-03-03-02  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use AccessManager AccessManager-00-07-39  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use jeformat jeformat-00-00-02  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use xmext xmext-01-02-12  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use Jers Jers-04-02-08  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use cmdl cmdl-01-05-02  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use omni omni-04-13-24  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use owl owl-00-02-16  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use config config-02-06-04  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use dal dal-02-01-09  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ipc ipc-05-06-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ResourceManager ResourceManager-01-01-14  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use rdb rdb-07-05-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use is is-09-12-07  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use TTCInfo TTCInfo-05-03-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use RCInfo RCInfo-01-01-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use TriggerCommander TriggerCommander-00-02-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use DataflowPolicy DataflowPolicy-01-06-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use DFExceptions DFExceptions-03-03-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use DFDebug DFDebug-02-00-22  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSGetInput ROSGetInput-02-00-07  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use rcc_error rcc_error-02-00-06  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use io_rcc io_rcc-02-00-50  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use rcc_time_stamp rcc_time_stamp-02-00-16  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use cmem_rcc cmem_rcc-02-00-32  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use vme_rcc vme_rcc-02-00-79  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use DFThreads DFThreads-02-05-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSUtilities ROSUtilities-02-07-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use DFSubSystemItem DFSubSystemItem-06-06-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ProcessManager ProcessManager-01-08-02  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use TestManager TestManager-01-13-03  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ExpertSystemInterface ExpertSystemInterface-00-05-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use emon emon-00-08-04  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use DFConfiguration DFConfiguration-10-03-05  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use dvs dvs-01-23-02  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use RunControl RunControl-00-10-10  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use oh oh-00-05-04  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use monsvc monsvc-00-04-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSObjectAllocation ROSObjectAllocation-02-01-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSMemoryPool ROSMemoryPool-02-02-09  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSEventInputManager ROSEventInputManager-02-02-07  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSBufferManagement ROSBufferManagement-02-04-08  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSEventFragment ROSEventFragment-02-04-04  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSRobin ROSRobin-00-01-110  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSslink ROSslink-02-00-15  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSfilar ROSfilar-02-00-45  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSCore ROSCore-12-07-02  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSInterruptScheduler ROSInterruptScheduler-01-02-00  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
use ROSModules ROSModules-03-02-01  (/afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00)
----------> tags
CMTv1 (from CMTVERSION)
CMTr25 (from CMTVERSION)
CMTp20130606 (from CMTVERSION)
Linux (from uname) package [CMT LCG_Platforms] implies [Unix host-linux]
x86_64-slc6-gcc48-opt (from CMTCONFIG) package [TDAQCPolicyInt LCG_Platforms] implies [x86_64 x86_64-slc6 linux slc6 gcc gcc48 opt x86_64-slc6-gcc48 gcc4 target-x86_64 target-slc6 target-gcc48 target-opt]
CERN (from CMTSITE)
ATLAS_DAQ_no_config (from PROJECT) excludes [ATLAS_DAQ_config]
ATLAS_DAQ_no_root (from PROJECT) excludes [ATLAS_DAQ_root]
ATLAS_DAQ_cleanup (from PROJECT) excludes [ATLAS_DAQ_no_cleanup]
ATLAS_DAQ_scripts (from PROJECT) excludes [ATLAS_DAQ_no_scripts]
ATLAS_DAQ_prototypes (from PROJECT) excludes [ATLAS_DAQ_no_prototypes]
ATLAS_DAQ_without_installarea (from PROJECT) excludes [ATLAS_DAQ_with_installarea]
ATLAS_DAQ_with_version_directory (from PROJECT) excludes [ATLAS_DAQ_without_version_directory]
tdaq_no_config (from PROJECT) excludes [tdaq_config]
tdaq_no_root (from PROJECT) excludes [tdaq_root]
tdaq_cleanup (from PROJECT) excludes [tdaq_no_cleanup]
tdaq_scripts (from PROJECT) excludes [tdaq_no_scripts]
tdaq_prototypes (from PROJECT) excludes [tdaq_no_prototypes]
tdaq_without_installarea (from PROJECT) excludes [tdaq_with_installarea]
tdaq_with_version_directory (from PROJECT) excludes [tdaq_without_version_directory]
dqm-common_no_config (from PROJECT) excludes [dqm-common_config]
dqm-common_no_root (from PROJECT) excludes [dqm-common_root]
dqm-common_cleanup (from PROJECT) excludes [dqm-common_no_cleanup]
dqm-common_scripts (from PROJECT) excludes [dqm-common_no_scripts]
dqm-common_prototypes (from PROJECT) excludes [dqm-common_no_prototypes]
dqm-common_without_installarea (from PROJECT) excludes [dqm-common_with_installarea]
dqm-common_with_version_directory (from PROJECT) excludes [dqm-common_without_version_directory]
tdaq-common_no_config (from PROJECT) excludes [tdaq-common_config]
tdaq-common_no_root (from PROJECT) excludes [tdaq-common_root]
tdaq-common_cleanup (from PROJECT) excludes [tdaq-common_no_cleanup]
tdaq-common_scripts (from PROJECT) excludes [tdaq-common_no_scripts]
tdaq-common_prototypes (from PROJECT) excludes [tdaq-common_no_prototypes]
tdaq-common_without_installarea (from PROJECT) excludes [tdaq-common_with_installarea]
tdaq-common_with_version_directory (from PROJECT) excludes [tdaq-common_without_version_directory]
ATLAS_DAQ (from PROJECT)
LCGCMT_no_config (from PROJECT) excludes [LCGCMT_config]
LCGCMT_no_root (from PROJECT) excludes [LCGCMT_root]
LCGCMT_cleanup (from PROJECT) excludes [LCGCMT_no_cleanup]
LCGCMT_scripts (from PROJECT) excludes [LCGCMT_no_scripts]
LCGCMT_prototypes (from PROJECT) excludes [LCGCMT_no_prototypes]
LCGCMT_without_installarea (from PROJECT) excludes [LCGCMT_with_installarea]
LCGCMT_with_version_directory (from PROJECT) excludes [LCGCMT_without_version_directory]
x86_64 (from package CMT) package [LCG_Platforms] implies [host-x86_64]
slc66 (from package CMT) package [LCG_Platforms] implies [host-slc6]
gcc481 (from package CMT)
Unix (from package CMT) package [LCG_Platforms] implies [host-unix] excludes [WIN32 Win32]
linux (from package TDAQCPolicyInt)
gcc (from package TDAQCPolicyInt)
opt (from package TDAQCPolicyInt)
gcc4 (from package TDAQCPolicyInt)
slc6 (from package TDAQCPolicyInt)
x86_64-slc6 (from package TDAQCPolicyInt)
gcc48 (from package TDAQCPolicyInt)
x86_64-slc6-gcc48 (from package TDAQCPolicyInt)
host-x86_64 (from package LCG_Platforms)
host-linux (from package LCG_Platforms) package [LCG_Platforms] implies [host-unix]
host-unix (from package LCG_Platforms)
host-slc6 (from package LCG_Platforms) package [LCG_Platforms] implies [host-slc]
host-slc (from package LCG_Platforms) package [LCG_Platforms] implies [host-linux]
target-opt (from package LCG_Platforms)
target-gcc48 (from package LCG_Platforms) package [LCG_Platforms] implies [target-gcc4 target-lcg-compiler lcg-compiler target-c11]
target-x86_64 (from package LCG_Platforms)
target-slc6 (from package LCG_Platforms) package [LCG_Platforms] implies [target-slc]
target-slc (from package LCG_Platforms) package [LCG_Platforms] implies [target-linux]
target-linux (from package LCG_Platforms) package [LCG_Platforms] implies [target-unix]
target-unix (from package LCG_Platforms)
target-gcc4 (from package LCG_Platforms) package [LCG_Platforms] implies [target-gcc]
target-lcg-compiler (from package LCG_Platforms)
lcg-compiler (from package LCG_Platforms)
target-c11 (from package LCG_Platforms)
target-gcc (from package LCG_Platforms)
ROOT_GE_5_15 (from package LCG_Configuration)
ROOT_GE_5_19 (from package LCG_Configuration)
----------> CMTPATH
# Add path /afs/cern.ch/user/d/daquser/public/ATLAS_DAQ/DataFlow from initialization
# Add path /afs/cern.ch/atlas/project/tdaq/inst/tdaq/tdaq-05-05-00 from ProjectPath
# Add path /afs/cern.ch/atlas/project/tdaq/inst/dqm-common/dqm-common-00-37-00 from ProjectPath
# Add path /afs/cern.ch/atlas/project/tdaq/inst/tdaq-common/tdaq-common-01-31-00 from ProjectPath
# Add path /afs/cern.ch/atlas/project/tdaq/inst/LCGCMT/LCGCMT_71 from ProjectPath
